### ISSUE TITLE
Index="all" deleted .kibana_1

### ISSUE THREAD

**Issue by Nuru** [cloudposse/terraform-aws-lambda-elasticsearch-cleanup#5]
## what
Using the [default index name of "all"](https://github.com/cloudposse/terraform-aws-lambda-elasticsearch-cleanup/blob/71674618e9ee49e7ab2d3f52571b5f320892fbf4/variables.tf#L33-L36), the lambda is supposed to leave the `.kibana` index alone. While technically it performs as advertised, when using AWS Elasticsearch 6.5 with built-in Kibana, the index is named `.kibana_1` and this lambda deletes it.

## solution
When given an index name of "all", the lambda probably should skip all indexes with names starting with `.kibana`, not just the 1 index exactly named `.kibana`

**Comment by pathikritmodak** [comment]
I submitted a PR to do exactly that - https://github.com/cloudposse/terraform-aws-lambda-elasticsearch-cleanup/pull/12

**Comment by Nuru** [comment]
The issue of what to do with the `.kibana_N` indexes is not clear cut. The Kibana 6.5 [docs](https://www.elastic.co/guide/en/kibana/6.5/upgrade-migrations.html) suggest that you will accumulate multiple indexes over time (`.kibana_1`, `.kibana_2`, `.kibana_3`, ...) and may or may not want to keep older versions to enable [rolling back](https://www.elastic.co/guide/en/kibana/6.5/upgrade-migrations.html#upgrade-migrations-rolling-back) to previous versions. 

The solution upstream is to explicitly list which indexes to skip when specifying delete `all`. That is dodgy, in that it makes it most likely that the newest and in-use index could get deleted if you forget to update the skip list first. 

For now, #14 closes this specific issue, in that it excludes `.kibana_1`, but we still recommend explicitly listing which indexes to delete (e.g. "logstash") instead.

**Comment by Nuru** [comment]
Closing due to #14, move further discussion to #12
