### ISSUE TITLE
LICENSE VIOLATED

### ISSUE THREAD

**Issue by giuliocalzolari** [cloudposse/terraform-aws-lambda-elasticsearch-cleanup#7]
Hi @joshmyers @osterman @Nuru 
are you aware that this repo is violating the original license of this code.

https://github.com/cloudreach/aws-lambda-es-cleanup/blob/master/LICENSE.md

can you please do a fork of the original repo and maintaining the original producer?

**Comment by Nuru** [comment]
@giuliocalzolari What part of the license do you feel is being violated? Although not required, https://github.com/cloudreach/aws-lambda-es-cleanup is being given credit [here](https://github.com/cloudposse/terraform-aws-lambda-elasticsearch-cleanup/blame/master/README.md#L14-L15)

Per [the license](http://www.apache.org/licenses/LICENSE-2.0):

> 4. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
>
>  a. You must give any other recipients of the Work or Derivative Works a copy of this License; and

Done from the start. https://github.com/cloudposse/terraform-aws-lambda-elasticsearch-cleanup/blob/master/LICENSE

> b. You must cause any modified files to carry prominent notices stating that You changed the files; and

The files used were not modified.

>  c. You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

Apologies, that was an oversight. The copyright notice has been added [here](https://github.com/cloudposse/terraform-aws-lambda-elasticsearch-cleanup/blob/master/lambda/COPYRIGHT.md).

> d. If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License. 

There was no "NOTICE" text file in the distribution, so this clause does not apply.

And that is all that is required by the license.

**Comment by giuliocalzolari** [comment]
thanks
